type Query {
  targetSummary(ensgId: String!): TargetSummary!
  targetDetailDrugs(ensgId: String!): TargetDetailDrugs!
  #   targetAssociations(
  #     ensgId: String!
  #     orderBy: Ordering
  #     size: Int
  #   ): TargetAssociations!
  diseaseSummary(efoId: String!): DiseaseSummary!
  diseaseDAG(efoId: String!): DiseaseDAG!
}
type TargetSummary {
  id: String!
  name: String!
  description: String
  symbol: String!
  synonyms: [String!]!
  drugs: TargetSummaryDrugs!
  pathways: TargetSummaryPathways!
  cancerBiomarkers: TargetSummaryCancerBiomarkers!
  chemicalProbes: TargetSummaryChemicalProbes!
  protein: TargetSummaryProtein!
  similarTargets: TargetSummarySimilarTargets!
}
type DiseaseSummary {
  id: String!
  name: String!
  synonyms: [String!]!
}
type DiseaseDAG {
  nodes: [DiseaseDAGNode!]!
}
type DiseaseDAGNode {
  id: String!
  name: String!
  parentIds: [String!]
  nodeType: String!
}
type TargetSummaryDrugs {
  count: Int!
  modalities: TargetDrugModalitiesAgg!
  trialsByPhase: [TargetDrugTrialsByPhaseAgg!]!
}
type TargetDrugModalitiesAgg {
  antibody: Boolean!
  peptide: Boolean!
  protein: Boolean!
  smallMolecule: Boolean!
}
type TargetDrugTrialsByPhaseAgg {
  phase: Int!
  trialCount: Int!
}
type TargetSummaryPathways {
  count: Int!
}
type TargetSummaryCancerBiomarkers {
  count: Int!
  diseaseCount: Int!
}
type TargetSummaryChemicalProbes {
  portalProbeCount: Int!
  hasProbeMinerLink: Boolean!
}
type TargetSummaryProtein {
  hasProtVista: Boolean!
  subcellularLocation: [String!]
}
type TargetSummarySimilarTargets {
  count: Int!
  averageCommonDiseases: Int!
}
type TargetDetailDrugs {
  rows: [EvidenceDrugsRow!]!
}
type EvidenceDrugsRow {
  targetId: String!
  targetSymbol: String!
  targetClass: String
  efoId: String!
  efoLabel: String!
  drugId: String!
  drugName: String!
  drugType: String!
  phase: Int!
  status: String
  activity: String
}

# type TargetAssociations {
#   associations: [TargetAssociation!]!
# }
# type TargetAssociation {
#   efoId: String!
#   efoLabel: String!
#   therapeuticAreaEfoId: String!
#   therapeuticAreaEfoLabel: String!
#   scoreOverall: Float!
#   scoresByDataType: [DataTypeScore!]!
# }
# type DataTypeScore {
#   dataType: String!
#   score: Float!
# }
# type Ordering {
#   field: String!
#   ascending: Boolean!
# }
